In [2]:
import numpy as np
scores = np.array([2.0, 1.0, 0.1])

def softmax_numpy(scores) : 
    return np.exp(scores)/np.sum(np.exp(scores), axis =0)

prob = softmax_numpy(scores)
print(prob)    

[0.65900114 0.24243297 0.09856589]


In [4]:
import tensorflow as tf
print(tf.__version__)

scores = tf.constant([2.0, 1.0, 0.1])
prob2 = tf.nn.softmax(scores)
print(prob2)

2.6.0
tf.Tensor([0.6590012  0.24243298 0.09856589], shape=(3,), dtype=float32)


In [ ]:
# ARGMAX

In [7]:
import numpy as np
a = np.array([(8, 2, 7), (3,4,5)])

print("Sum of Columns")
sumColumns = a.sum(axis = 0)
print(sumColumns)

print("Sum of Rows")
sumRows = a.sum(axis = 1)
print(sumRows)

Sum of Columns
[11  6 12]
Sum of Rows
[17 12]


In [11]:
import numpy as np
a = np.array([(8, 2, 7), (3,4,5)])

print("Index of maximum column")
indexColumns = a.argmax(axis = 0)
print(indexColumns)

print("Index of maximum row")
indexRows = a.argmax(axis = 1)
print(indexRows)

Index of maximum column
[0 1 0]
Index of maximum row
[0 2]


In [ ]:
print("Sum of Columns")
sumColumns = a.sum(axis = 0)
print(sumColumns)

print("Sum of Rows")
sumRows = a.sum(axis = 1)
print(sumRows)

Sum of Columns
[11  6 12]
Sum of Rows
[17 12]


In [12]:
inputData = tf.constant([[10,20]])
print(inputData.shape)
print(inputData)

#################### layer 1

W1 = tf.constant([[1,2,3], [4,5,6]])
print(W1.shape)
print(W1)

##############################

print("Index of maximum row")
indexRows = tf.argmax(a, axis = 1)
print(indexRows)

tf.Tensor(
[[8 2 7]
 [3 4 5]], shape=(2, 3), dtype=int32)
Index of maximum column
tf.Tensor([0 1 0], shape=(3,), dtype=int64)
Index of maximum row
tf.Tensor([0 2], shape=(2,), dtype=int64)


In [ ]:
inputData = tf.constant([[10,20]])
print(inputData.shape)
print(inputData)

#################### layer 1

W1 = tf.constant([[1,2,3], [4,5,6]])
print(W1.shape)
print(W1)

##############################








tf.Tensor(
[[8 2 7]
 [3 4 5]], shape=(2, 3), dtype=int32)
Index of maximum column
tf.Tensor([0 1 0], shape=(3,), dtype=int64)
Index of maximum row
tf.Tensor([0 2], shape=(2,), dtype=int64)


In [ ]:
inputData = tf.constant([[10,20]])
print(inputData.shape)
print(inputData)

#################### layer 1

W1 = tf.constant([[1,2,3], [4,5,6]])
print(W1.shape)
print(W1)

##############################




tf.Tensor(
[[8 2 7]
 [3 4 5]], shape=(2, 3), dtype=int32)
Index of maximum column
tf.Tensor([0 1 0], shape=(3,), dtype=int64)
Index of maximum row
tf.Tensor([0 2], shape=(2,), dtype=int64)


In [15]:
##############################
##############################

inputData = tf.constant([[10,20]])
print(inputData.shape)
print(inputData)

#################### layer 1
##############################

W1 = tf.constant([[1,2,3], [4,5,6]])
print(W1.shape)
print(W1)

##############################

b1 = tf.constant([[7,8,9]])
print(b1.shape)
print(b1)

##############################

outputH1 = tf.matmul(inputData, W1) + b1
print(outputH1.shape)
print(outputH1)

outputH1_Activation = tf.sigmoid(tf.cast(outputH1, tf.float32))
print(outputH1_Activation.shape)
print(outputH1_Activation)

##############################

W2 = tf.cast(tf.constant([[10], [11], [12], tf.float32)
print(W2.shape)
print(W2)

##############################

b2 = tf.cast(tf.constant([[13]], tf.float32)
print(b2.shape)
print(b2)

##############################

outputH2 = tf.matmul(outputH1_Activation, W2) + b2
print(outputH2.shape)
print(outputH2)

outputH2_Activation = tf.sigmoid(tf.cast(outputH2, tf.float32))
print(outputH2_Activation.shape)
print(outputH2_Activation)

##############################
##############################

(1, 2)
tf.Tensor([[10 20]], shape=(1, 2), dtype=int32)
(2, 3)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(1, 3)
tf.Tensor([[7 8 9]], shape=(1, 3), dtype=int32)
(1, 3)
tf.Tensor([[ 97 128 159]], shape=(1, 3), dtype=int32)
(1, 3)
tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)


In [45]:
import tensorflow as tf

#############################
##############################

inputData = tf.constant([[0.1,0.2]])
# print(inputData.shape)
# print(inputData)

#################### layer 1
##############################

W1 = tf.constant([[0.15], [0.05]])
# print(W1.shape)
# print(W1)

##############################

b1 = tf.constant([[0.33]])
# print(b1.shape)
# print(b1)

##############################

outputH1 = tf.matmul(inputData, W1) + b1
# print(outputH1.shape)
# print(outputH1)

outputH1_Activation = tf.keras.activations.relu(tf.cast(outputH1, tf.float32))
# print(outputH1_Activation.shape)
# print(outputH1_Activation)

##############################

W2 = tf.constant([[0.36]])
# print(W2.shape)
# print(W2)

##############################

b2 = tf.constant([[0.56]])
# print(b2.shape)
# print(b2)

##############################

outputH2 = tf.matmul(outputH1_Activation, W2) + b2
# print(outputH2.shape)
# print(outputH2)

outputH2_Activation = tf.keras.activations.relu(tf.cast(outputH2, tf.float32))
# print(outputH2_Activation.shape)
# print(outputH2_Activation)

##############################
##############################

print(outputH1_Activation)
print(outputH2_Activation)

tf.Tensor([[0.35500002]], shape=(1, 1), dtype=float32)
tf.Tensor([[0.68780005]], shape=(1, 1), dtype=float32)


In [73]:
import tensorflow as tf

x1 = -4.0
x2 = 0.5
x3 = 4.0 

gradient_SIGMOID1 = tf.keras.activations.sigmoid(x1) * (1- tf.keras.activations.sigmoid(x1))
print(gradient_SIGMOID1)

gradient_SIGMOID2 = tf.keras.activations.sigmoid(x2) * (1- tf.keras.activations.sigmoid(x2))
print(gradient_SIGMOID2)

gradient_SIGMOID3 = tf.keras.activations.sigmoid(x3) * (1- tf.keras.activations.sigmoid(x3))
print(gradient_SIGMOID3)

tf.Tensor(0.017662734, shape=(), dtype=float32)
tf.Tensor(0.23500372, shape=(), dtype=float32)
tf.Tensor(0.017662734, shape=(), dtype=float32)


In [76]:
import tensorflow as tf

x1 = -4.0
x2 = 0.5
x3 = 4.0 

gradient_TANH1 = 1 - tf.keras.activations.tanh(x1)**2
print(gradient_TANH1)

gradient_TANH2 = 1 - tf.keras.activations.tanh(x2)**2
print(gradient_TANH2)

gradient_TANH3 = 1- tf.keras.activations.tanh(x3)**2
print(gradient_TANH3)

tf.Tensor(0.0013411045, shape=(), dtype=float32)
tf.Tensor(0.7864477, shape=(), dtype=float32)
tf.Tensor(0.0013411045, shape=(), dtype=float32)


In [79]:
x1 = -4.0
x2 = 0.5
x3 = 4.0 

gradient_RELU = (lambda x: 1 if ( x > 0) else 0)(x1)
print(gradient_RELU)

gradient_RELU = (lambda x: 1 if ( x > 0) else 0)(x2)
print(gradient_RELU)

gradient_RELU = (lambda x: 1 if ( x > 0) else 0)(x3)
print(gradient_RELU)



0
1
1


In [ ]:
## PROBLEM 3
## here working on the PROBLEM 3, according to the SLIDE 22 in the presentation 

0


In [ ]:
# the SYNTAX is DIFFERENT than the syntax that was provided in the file with the ANSWERS

In [5]:
import tensorflow as tf
print(tf.__version__)
##############################

SCORES1 =  tf.constant([2.3, 1.2, 0.3, 0.0])
PROBAB1 = tf.nn.softmax(SCORES1)
print(PROBAB1) 

##############################

SCORES2 =  tf.constant([1.9, 1.7, 2.6, 0.2, 1.3])
PROBAB2 = tf.nn.softmax(SCORES2)
print(PROBAB2) 

2.6.0
tf.Tensor([0.6375659  0.21222727 0.08628516 0.06392162], shape=(4,), dtype=float32)
tf.Tensor([0.21910708 0.17938972 0.44122744 0.04002725 0.12024851], shape=(5,), dtype=float32)


In [ ]:
import tensorflow as tf
print(tf.__version__)
##############################

SCORES1 =  tf.constant([2.3, 1.2, 0.3, 0.0])
PROBAB1 = tf.nn.softmax(SCORES1)
print(PROBAB1) 

##############################

SCORES2 =  tf.constant([1.9, 1.7, 2.6, 0.2, 1.3])
PROBAB2 = tf.nn.softmax(SCORES2)
print(PROBAB2) 



2.6.0
tf.Tensor([0.6375659  0.21222727 0.08628516 0.06392162], shape=(4,), dtype=float32)
tf.Tensor([0.21910708 0.17938972 0.44122744 0.04002725 0.12024851], shape=(5,), dtype=float32)


In [ ]:
## PROBLEM 4, regarding the CROSS-ENTROPY, according to the SLIDE 24 of the presentation

In [ ]:
## the SYNTAX is DIFFERENT than the syntax that was provided in the file with the ANSWERS

In [42]:
import tensorflow as tf
print(tf.__version__)
import math
import numpy as np

############################## here we define a function that we call CROSS-ENTROPY
def CROSS_ENTROPY (TARGET, COMPUTED) :
    z = -1 * ( TARGET * math.log(COMPUTED) + (1-TARGET) * math.log(1-COMPUTED) )
    return z  
##############################

TARGET1 = tf.constant([0.0, 0.0, 0.0, 0.0, 0.0])
COMPUTED1 = tf.constant([0.95, 0.8, 0.6, 0.4, 0.1])

# using the NATURAL LOGARITHM
print("        ")

for i in range(len(TARGET1)) : 
    # print(CROSS_ENTROPY(TARGET1[i], COMPUTED1[i]))
    print('Computed value is', np.array(COMPUTED1[i]) , 'Cost function is', np.array(CROSS_ENTROPY(TARGET1[i], COMPUTED1[i]))) 

# using a a line to separate
print("        ")

TARGET2 = tf.constant([1.0, 1.0, 1.0, 1.0, 1.0])
COMPUTED2 = tf.constant([0.95, 0.8, 0.6, 0.4, 0.1])

for i in range(len(TARGET2)) : 
    # print(CROSS_ENTROPY(TARGET2[i], COMPUTED2[i]))
    print('Computed value is', np.array(COMPUTED2[i]) , 'Cost function is', np.array(CROSS_ENTROPY(TARGET2[i], COMPUTED2[i]))) 

2.6.0
        
Computed value is 0.95 Cost function is 2.995732
Computed value is 0.8 Cost function is 1.609438
Computed value is 0.6 Cost function is 0.9162908
Computed value is 0.4 Cost function is 0.5108256
Computed value is 0.1 Cost function is 0.105360545
        
Computed value is 0.95 Cost function is 0.051293306
Computed value is 0.8 Cost function is 0.22314353
Computed value is 0.6 Cost function is 0.5108256
Computed value is 0.4 Cost function is 0.9162907
Computed value is 0.1 Cost function is 2.3025851


In [ ]:

# working on the PROBLEM 5
# according to the SLIDE 26


In [50]:
import tensorflow as tf
print(tf.__version__)
import math
import numpy as np


a = tf.constant( [ [5,2,3], [26, 56, 92], [3, 0, 26] ])
print(np.array(x))

print("the index of the maximum column")
a1 = tf.argmax(a, axis = 0 )
print(np.array(a1))

print("the index of the maximum row")
a2 = tf.argmax(a, axis = 1 )
print(np.array(a2))

2.6.0
[[ 5  2  3]
 [26 56 92]
 [ 3  0 26]]
the index of the maximum column
[1 1 1]
the index of the maximum row
[0 2 2]


In [ ]:
# working on PROBLEM 6
# we have adapted a previous code a PREVIOUS PROBLEM

# in the first BATCH, the INPUT is [0,0], and the OUTPUT is 0
# in the first BATCH, the INPUT is [1,0], and the OUTPUT is 1
# in the first BATCH, the INPUT is [0,1], and the OUTPUT is 1
# in the first BATCH, the INPUT is [1,1], and the OUTPUT is 0


In [ ]:
# shall we use a BATCH SIZE of 1

In [75]:
import tensorflow as tf

############################## the INPUT data is here 0, 0
##############################

inputData = tf.constant([[0, 0]])

W1 = tf.constant([[-4, -6, -5], [3, 6, 4 ]])
b1 = tf.constant([[-2 , 3 , -2]])

outputH1 = tf.matmul(inputData, W1) + b1
outputH1_Activation = tf.keras.activations.sigmoid(tf.cast(outputH1, tf.float32))

##############################

W2 = tf.constant([ [5], [-9], [7] ], tf.float32)
b2 = tf.constant([[4]], tf.float32)

outputH2 = tf.matmul(outputH1_Activation, W2) + b2
outputH2_Activation = tf.keras.activations.sigmoid(tf.cast(outputH2, tf.float32))

##############################
##############################

print(np.array(outputH1_Activation))
print(np.array(outputH2_Activation))

##############################
##############################

# the OUTPUT that we do have is

# the TRUE OUTPUT is 0
# so we do compute the ERROR

TRUE_OUTPUT1 = 0

ERROR1 = (TRUE_OUTPUT1 - outputH2_Activation ) ** 2

print(np.array([ERROR1]))
##############################
##############################

[[0.11920291 0.95257413 0.11920291]]
[[0.04137862]]
[[[0.00171219]]]


In [ ]:
# shall we use a BATCH SIZE of 1

In [76]:
import tensorflow as tf

############################## the INPUT data is here 1, 0
##############################

inputData = tf.constant([[1, 0]])

W1 = tf.constant([[-4, -6, -5], [3, 6, 4 ]])
b1 = tf.constant([[-2 , 3 , -2]])

outputH1 = tf.matmul(inputData, W1) + b1
outputH1_Activation = tf.keras.activations.sigmoid(tf.cast(outputH1, tf.float32))

##############################

W2 = tf.constant([ [5], [-9], [7] ], tf.float32)
b2 = tf.constant([[4]], tf.float32)

outputH2 = tf.matmul(outputH1_Activation, W2) + b2
outputH2_Activation = tf.keras.activations.sigmoid(tf.cast(outputH2, tf.float32))

##############################
##############################

print(np.array(outputH1_Activation))
print(np.array(outputH2_Activation))

##############################
##############################

# the OUTPUT that we do have is

# the TRUE OUTPUT is 1
# so we do compute the ERROR

TRUE_OUTPUT2 = 1

ERROR2 = (TRUE_OUTPUT2 - outputH2_Activation ) ** 2

print(np.array([ERROR2]))
##############################
##############################

[[0.00247264 0.04742587 0.00091106]]
[[0.9731927]]
[[[0.00071863]]]


In [ ]:
# shall we use a BATCH SIZE of 1

In [77]:
import tensorflow as tf

############################## the INPUT data is here 0, 1
##############################

inputData = tf.constant([[0, 1]])

W1 = tf.constant([[-4, -6, -5], [3, 6, 4 ]])
b1 = tf.constant([[-2 , 3 , -2]])

outputH1 = tf.matmul(inputData, W1) + b1
outputH1_Activation = tf.keras.activations.sigmoid(tf.cast(outputH1, tf.float32))

##############################

W2 = tf.constant([ [5], [-9], [7] ], tf.float32)
b2 = tf.constant([[4]], tf.float32)

outputH2 = tf.matmul(outputH1_Activation, W2) + b2
outputH2_Activation = tf.keras.activations.sigmoid(tf.cast(outputH2, tf.float32))

##############################
##############################

print(np.array(outputH1_Activation))
print(np.array(outputH2_Activation))

##############################
##############################

# the OUTPUT that we do have is

# the TRUE OUTPUT is 1
# so we do compute the ERROR

TRUE_OUTPUT3 = 1

ERROR3 = (TRUE_OUTPUT3 - outputH2_Activation ) ** 2

print(np.array([ERROR3]))
##############################
##############################

[[0.7310586 0.9998766 0.8807971]]
[[0.99201345]]
[[[6.378491e-05]]]


In [ ]:
# shall we use a BATCH SIZE of 1

In [79]:
import tensorflow as tf

############################## the INPUT data is here 1, 1
##############################

inputData = tf.constant([[1, 1]])

W1 = tf.constant([[-4, -6, -5], [3, 6, 4 ]])
b1 = tf.constant([[-2 , 3 , -2]])

outputH1 = tf.matmul(inputData, W1) + b1
outputH1_Activation = tf.keras.activations.sigmoid(tf.cast(outputH1, tf.float32))

##############################

W2 = tf.constant([ [5], [-9], [7] ], tf.float32)
b2 = tf.constant([[4]], tf.float32)

outputH2 = tf.matmul(outputH1_Activation, W2) + b2
outputH2_Activation = tf.keras.activations.sigmoid(tf.cast(outputH2, tf.float32))

##############################
##############################

print(np.array(outputH1_Activation))
print(np.array(outputH2_Activation))

##############################
##############################

# the OUTPUT that we do have is

# the TRUE OUTPUT is 1
# so we do compute the ERROR

TRUE_OUTPUT4 = 0

ERROR4 = (TRUE_OUTPUT4 - outputH2_Activation ) ** 2

print(np.array([ERROR4]))
##############################
##############################

[[0.04742587 0.95257413 0.04742587]]
[[0.01791471]]
[[[0.00032094]]]


In [ ]:
# shall we use a BATCH SIZE of 4

In [85]:
##############################

import tensorflow as tf

############################## the INPUT data is here 1, 1
##############################

inputData = tf.constant([[0,0], [1,0], [0,1], [1, 1]])

W1 = tf.constant([[-4, -6, -5], [3, 6, 4 ]])
b1 = tf.constant([[-2 , 3 , -2]])

outputH1 = tf.matmul(inputData, W1) + b1
outputH1_Activation = tf.keras.activations.sigmoid(tf.cast(outputH1, tf.float32))

##############################

W2 = tf.constant([ [5], [-9], [7] ], tf.float32)
b2 = tf.constant([[4]], tf.float32)

outputH2 = tf.matmul(outputH1_Activation, W2) + b2
outputH2_Activation = tf.keras.activations.sigmoid(tf.cast(outputH2, tf.float32))

##############################
##############################

# print(np.array(outputH1_Activation))
# print(np.array(outputH2_Activation))

##############################
##############################

# the OUTPUT that we do have is

# the TRUE OUTPUT is 0, 1, 1, 0
# so we do compute the ERROR

TRUE_OUTPUT4 = tf.constant( [ [0.0], [1.0], [1.0], [0.0] ] )

ERROR4 = (TRUE_OUTPUT4 - outputH2_Activation ) ** 2

print("here it is the ERROR that we do obtain for each INPUT type")
print(np.array([ERROR4]))
##############################
##############################

here it is the ERROR that we do obtain for each INPUT type
[[[1.7121900e-03]
  [7.1863178e-04]
  [6.3784908e-05]
  [3.2093693e-04]]]
