In [2]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [3]:
import keras as ks
print(ks.__version__)

2.6.0


**PROBLEM 2**

In [26]:
x = tf.constant([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])
y = tf.constant([34, 28, 45, 67, 89, 93, 24, 49, 11, 7])
z = tf.add(x,y)
print(z)

tf.Tensor([134 129 147 170 193 198 130 156 119 116], shape=(10,), dtype=int32)


**PROBLEM 3**

In [30]:
x1 = tf.constant([ [ 1, 2, 3, 4], [5, 6, 7, 8] ])
z = tf.stack([x1, x1])
print(z)
print(z.shape)

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]], shape=(2, 2, 4), dtype=int32)
(2, 2, 4)


**PROBLEM 4**

In [31]:
y = tf.stack([x1])
print(y)
print(y.shape)


tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]], shape=(1, 2, 4), dtype=int32)
(1, 2, 4)


**PROBLEM 5**

In [33]:
x1 = tf.constant([ [ 1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ])
z = tf.reshape(x1, [6,2])
print(z)
print(z.shape)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]], shape=(6, 2), dtype=int32)
(6, 2)


**PROBLEM 6**

In [34]:
a = 1.12
b = 2.34
c = 0.72
d = 0.81
f = 19.83

In [37]:
t = tf.constant(1+a/b+c/f**2)
print(t)

tf.Tensor(1.4804635, shape=(), dtype=float32)


In [39]:
s = tf.constant((b-a)/(d-c))
print(s)

tf.Tensor(13.555555, shape=(), dtype=float32)


In [40]:
r = tf.constant(1/ (1/a + 1/b + 1/c + 1/d ))
print(r)


tf.Tensor(0.25357127, shape=(), dtype=float32)


In [43]:
y = a * b * f**2 / (2 * c)
print(y)

715.676598


**PROBLEM 7**

In [ ]:
# ASSOCIATIVE PROPERTY

In [45]:
A = tf.constant([ [ 4, -2, 1], [6, 8, -5], [7, 9, 10] ])
# print(A)


In [47]:
B = tf.constant([ [ 6, 9, -4], [7, 5, 3], [-8, 2, 1] ])
# print(B)


In [49]:
C = tf.constant([ [ -4, -5, 2], [10, 6, 1], [3, -9, 8] ])
# print(C)


In [52]:
D = tf.matmul(A, B+C)
print(D)

tf.Tensor(
[[-31 -13  -7]
 [173 147 -25]
 [117  57 112]], shape=(3, 3), dtype=int32)


In [54]:
E = tf.matmul(A,B) + tf.matmul(A,C)
print(E)

tf.Tensor(
[[-31 -13  -7]
 [173 147 -25]
 [117  57 112]], shape=(3, 3), dtype=int32)


In [55]:
# DISTRIBUTIVE PROPERTY

In [56]:
F = tf.matmul(tf.matmul(A,B), C)
print(F)

tf.Tensor(
[[ 209  347 -136]
 [ 297 -111  308]
 [1207  562  250]], shape=(3, 3), dtype=int32)


In [58]:
G = tf.matmul(A, tf.matmul(B, C))
print(G)

tf.Tensor(
[[ 209  347 -136]
 [ 297 -111  308]
 [1207  562  250]], shape=(3, 3), dtype=int32)
