In [58]:
import numpy as np
from scipy import signal as sg
import tensorflow as tf
import keras as ks

In [59]:
# the SOLUTION with SCIPY

In [60]:
I = np.array([ [97,52,99,62,69,45,70], [99,14,60,50,74,45,22], [59,72,74,14,74,100,28], [28,2,47,85,2,88,77], [74,6,30,87,49,22,43], [86,87,4,53,36,10,46] , [54,7,67,23,29,26,5]], dtype=object)
print(I.shape)


(7, 7)


In [61]:
g = np.array([ [1,2,1], [2,4,2], [1,2,1] ],dtype=object)
print(g.shape)

(3, 3)


In [62]:
sg.convolve(I,g)

array([[97, 246, 300, 312, 292, 245, 229, 185, 70],
       [293, 704, 787, 808, 818, 733, 644, 459, 162],
       [354, 860, 951, 914, 936, 993, 903, 519, 142],
       [245, 650, 820, 833, 805, 944, 1045, 643, 155],
       [189, 460, 551, 749, 867, 823, 948, 748, 225],
       [262, 625, 575, 635, 871, 726, 629, 560, 209],
       [300, 787, 779, 613, 687, 584, 426, 348, 140],
       [194, 489, 534, 476, 430, 349, 274, 174, 56],
       [54, 115, 135, 164, 142, 107, 86, 36, 5]], dtype=object)

In [63]:
sg.convolve(I,g, mode="full")

array([[97, 246, 300, 312, 292, 245, 229, 185, 70],
       [293, 704, 787, 808, 818, 733, 644, 459, 162],
       [354, 860, 951, 914, 936, 993, 903, 519, 142],
       [245, 650, 820, 833, 805, 944, 1045, 643, 155],
       [189, 460, 551, 749, 867, 823, 948, 748, 225],
       [262, 625, 575, 635, 871, 726, 629, 560, 209],
       [300, 787, 779, 613, 687, 584, 426, 348, 140],
       [194, 489, 534, 476, 430, 349, 274, 174, 56],
       [54, 115, 135, 164, 142, 107, 86, 36, 5]], dtype=object)

In [64]:
sg.convolve(I,g, mode="valid")

array([[951, 914, 936, 993, 903],
       [820, 833, 805, 944, 1045],
       [551, 749, 867, 823, 948],
       [575, 635, 871, 726, 629],
       [779, 613, 687, 584, 426]], dtype=object)

In [75]:
Itf = tf.convert_to_tensor(I.astype(float))
Itf.shape
ITF = tf.reshape(Itf, [1,7,7,1])
# print(ITF)


In [76]:
gtf = tf.convert_to_tensor(g.astype(float))
gtf.shape
GTF = tf.reshape(gtf, [3,3,1,1])
# print(GTF)

In [79]:
op1 = tf.nn.conv2d(ITF, GTF, strides = [1,1,1,1], padding = "VALID")
op2 = tf.nn.conv2d(ITF, GTF, strides = [1,1,1,1], padding = "SAME")

In [90]:
print(op1.numpy()[:1,:1])

[[[[951.]
   [914.]
   [936.]
   [993.]
   [903.]]]]


In [91]:
print(op2.numpy()[:1,:1])

[[[[704.]
   [787.]
   [808.]
   [818.]
   [733.]
   [644.]
   [459.]]]]
